//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galssoft.VKontakteWM.Notification.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Galssoft.VKontakteWM.Notification.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon BothEvMes {
            get {
                object obj = ResourceManager.GetObject("BothEvMes", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon Events {
            get {
                object obj = ResourceManager.GetObject("Events", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start service (file {0} not found or is not available).
        /// </summary>
        internal static string Interprocess_StartService_FileNotFound {
            get {
                return ResourceManager.GetString("Interprocess_StartService_FileNotFound", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon Messages {
            get {
                object obj = ResourceManager.GetObject("Messages", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрыть.
        /// </summary>
        internal static string Program_LeftSoftKey {
            get {
                return ResourceManager.GetString("Program_LeftSoftKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program start error.
        /// </summary>
        internal static string Program_OnNtfnRSoftKey_Error {
            get {
                return ResourceManager.GetString("Program_OnNtfnRSoftKey_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас на сайте ВКонтакте.
        /// </summary>
        internal static string Program_OnNtfnShow_Caption {
            get {
                return ResourceManager.GetString("Program_OnNtfnShow_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service application error.
        /// </summary>
        internal static string Program_OnTimerTick_Error {
            get {
                return ResourceManager.GetString("Program_OnTimerTick_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новых комментариев.
        /// </summary>
        internal static string Program_OnTimerTick_NfnCmnts {
            get {
                return ResourceManager.GetString("Program_OnTimerTick_NfnCmnts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification output error.
        /// </summary>
        internal static string Program_OnTimerTick_NfnError {
            get {
                return ResourceManager.GetString("Program_OnTimerTick_NfnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новых друзей.
        /// </summary>
        internal static string Program_OnTimerTick_NfnFrnds {
            get {
                return ResourceManager.GetString("Program_OnTimerTick_NfnFrnds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новостей друзей.
        /// </summary>
        internal static string Program_OnTimerTick_NfnFrndsNs {
            get {
                return ResourceManager.GetString("Program_OnTimerTick_NfnFrndsNs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фотографий друзей.
        /// </summary>
        internal static string Program_OnTimerTick_NfnFrndsPh {
            get {
                return ResourceManager.GetString("Program_OnTimerTick_NfnFrndsPh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новых сообщений.
        /// </summary>
        internal static string Program_OnTimerTick_NfnMess {
            get {
                return ResourceManager.GetString("Program_OnTimerTick_NfnMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщений стены.
        /// </summary>
        internal static string Program_OnTimerTick_NfnWallMsgs {
            get {
                return ResourceManager.GetString("Program_OnTimerTick_NfnWallMsgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть.
        /// </summary>
        internal static string Program_RightSoftKey {
            get {
                return ResourceManager.GetString("Program_RightSoftKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление в роуминге.
        /// </summary>
        internal static string RenewInRoam {
            get {
                return ResourceManager.GetString("RenewInRoam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: no timer data in registry ({0}).
        /// </summary>
        internal static string ServiceApplication_noTimerDataError {
            get {
                return ResourceManager.GetString("ServiceApplication_noTimerDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer data format error ({0}).
        /// </summary>
        internal static string ServiceApplication_timerDataFormatError {
            get {
                return ResourceManager.GetString("ServiceApplication_timerDataFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer data format overflow error ({0}).
        /// </summary>
        internal static string ServiceApplication_timerDataOverflowError {
            get {
                return ResourceManager.GetString("ServiceApplication_timerDataOverflowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закачивать статусы друзей.
        /// </summary>
        internal static string UpdateFriendsStatus {
            get {
                return ResourceManager.GetString("UpdateFriendsStatus", resourceCulture);
            }
        }
    }
}
