//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galssoft.VKontakteWM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Galssoft.VKontakteWM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        internal static string AboutView_btnUpdate_Text_Update {
            get {
                return ResourceManager.GetString("AboutView_btnUpdate_Text_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        internal static string AboutView_Button_Back {
            get {
                return ResourceManager.GetString("AboutView_Button_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загр. фото.
        /// </summary>
        internal static string AboutView_Button_Photo {
            get {
                return ResourceManager.GetString("AboutView_Button_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы хотите перейти на сайт поддержки?.
        /// </summary>
        internal static string AboutView_Button_Support {
            get {
                return ResourceManager.GetString("AboutView_Button_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        internal static string AboutView_Button_Update {
            get {
                return ResourceManager.GetString("AboutView_Button_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверить обновления.
        /// </summary>
        internal static string AboutView_CheckUpdateButton {
            get {
                return ResourceManager.GetString("AboutView_CheckUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВКонтакте Windows Mobile.
        /// </summary>
        internal static string AboutView_lblApplicationTitle_Text {
            get {
                return ResourceManager.GetString("AboutView_lblApplicationTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо скачать новую версию!.
        /// </summary>
        internal static string AboutView_lblVersionIsMandatory_Text {
            get {
                return ResourceManager.GetString("AboutView_lblVersionIsMandatory_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сделано в .
        /// </summary>
        internal static string AboutView_MadeBy {
            get {
                return ResourceManager.GetString("AboutView_MadeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Еще.
        /// </summary>
        internal static string AboutView_MenuItem_Add {
            get {
                return ResourceManager.GetString("AboutView_MenuItem_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверить.
        /// </summary>
        internal static string AboutView_MenuItem_Check {
            get {
                return ResourceManager.GetString("AboutView_MenuItem_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сайт поддержки....
        /// </summary>
        internal static string AboutView_MenuItem_Support {
            get {
                return ResourceManager.GetString("AboutView_MenuItem_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        internal static string AboutView_MenuItem_Update {
            get {
                return ResourceManager.GetString("AboutView_MenuItem_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программе.
        /// </summary>
        internal static string AboutView_Text {
            get {
                return ResourceManager.GetString("AboutView_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка обновления успешно выполнена!.
        /// </summary>
        internal static string AboutView_UpdateCompleteDialog_Text {
            get {
                return ResourceManager.GetString("AboutView_UpdateCompleteDialog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновления.
        /// </summary>
        internal static string AboutView_Updates {
            get {
                return ResourceManager.GetString("AboutView_Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скачать версию .
        /// </summary>
        internal static string AboutView_UploadUpdateButton {
            get {
                return ResourceManager.GetString("AboutView_UploadUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У Вас установлена свежая версия.
        /// </summary>
        internal static string ApplicationUpdate_Message_AlreadyInstall {
            get {
                return ResourceManager.GetString("ApplicationUpdate_Message_AlreadyInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступна версия .
        /// </summary>
        internal static string ApplicationUpdate_Message_MayInstall {
            get {
                return ResourceManager.GetString("ApplicationUpdate_Message_MayInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно выполнить проверку обновления!.
        /// </summary>
        internal static string ApplicationUpdate_Message_Undefined {
            get {
                return ResourceManager.GetString("ApplicationUpdate_Message_Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При старте.
        /// </summary>
        internal static string AutoUpdateAtStart {
            get {
                return ResourceManager.GetString("AutoUpdateAtStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление при старте.
        /// </summary>
        internal static string AutoUpdateAtStart1 {
            get {
                return ResourceManager.GetString("AutoUpdateAtStart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нотификация.
        /// </summary>
        internal static string BackgroundNotification {
            get {
                return ResourceManager.GetString("BackgroundNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция выполнена с ошибкой.
        /// </summary>
        internal static string CallNumberResponseMessage_Unsuccess {
            get {
                return ResourceManager.GetString("CallNumberResponseMessage_Unsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подпись.
        /// </summary>
        internal static string ChangeCommentView_Title {
            get {
                return ResourceManager.GetString("ChangeCommentView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        internal static string ChangeStatus_Title {
            get {
                return ResourceManager.GetString("ChangeStatus_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string ChangeStatusView_Cancel {
            get {
                return ResourceManager.GetString("ChangeStatusView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string ChangeStatusView_DeleteStatus {
            get {
                return ResourceManager.GetString("ChangeStatusView_DeleteStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить.
        /// </summary>
        internal static string ChangeStatusView_ResetStatus {
            get {
                return ResourceManager.GetString("ChangeStatusView_ResetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить.
        /// </summary>
        internal static string ChangeStatusView_SetStatus {
            get {
                return ResourceManager.GetString("ChangeStatusView_SetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус обновлен!.
        /// </summary>
        internal static string ChangeStatusView_SetStatusSuccess {
            get {
                return ResourceManager.GetString("ChangeStatusView_SetStatusSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смена статуса.
        /// </summary>
        internal static string ChangeStatusView_Title {
            get {
                return ResourceManager.GetString("ChangeStatusView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подпись....
        /// </summary>
        internal static string CommentControl_TextSubstitute {
            get {
                return ResourceManager.GetString("CommentControl_TextSubstitute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позвонить на мобильный.
        /// </summary>
        internal static string ContextMenu_CallNumber {
            get {
                return ResourceManager.GetString("ContextMenu_CallNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить в записную книжку.
        /// </summary>
        internal static string ContextMenu_SaveNumber {
            get {
                return ResourceManager.GetString("ContextMenu_SaveNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Написать комментарий.
        /// </summary>
        internal static string ContextMenu_SendComment {
            get {
                return ResourceManager.GetString("ContextMenu_SendComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить сообщение.
        /// </summary>
        internal static string ContextMenu_SendMessade {
            get {
                return ResourceManager.GetString("ContextMenu_SendMessade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить SMS.
        /// </summary>
        internal static string ContextMenu_SendSms {
            get {
                return ResourceManager.GetString("ContextMenu_SendSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посмотреть комменарии.
        /// </summary>
        internal static string ContextMenu_ViewComments {
            get {
                return ResourceManager.GetString("ContextMenu_ViewComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать.
        /// </summary>
        internal static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вырезать.
        /// </summary>
        internal static string CutToClipboard {
            get {
                return ResourceManager.GetString("CutToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление данных....
        /// </summary>
        internal static string DataLoading {
            get {
                return ResourceManager.GetString("DataLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление данных.
        /// </summary>
        internal static string DataRefreshing {
            get {
                return ResourceManager.GetString("DataRefreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled Image.
        /// </summary>
        internal static string DefaultFileNameToSave {
            get {
                return ResourceManager.GetString("DefaultFileNameToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        internal static string DefaultGroupHeader {
            get {
                return ResourceManager.GetString("DefaultGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не обновлять.
        /// </summary>
        internal static string DontUpdate {
            get {
                return ResourceManager.GetString("DontUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обрезать.
        /// </summary>
        internal static string EditPhoto_Designer_btnCropImage_Text {
            get {
                return ResourceManager.GetString("EditPhoto_Designer_btnCropImage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CW.
        /// </summary>
        internal static string EditPhoto_Designer_btnRotareImageClockwise_Text {
            get {
                return ResourceManager.GetString("EditPhoto_Designer_btnRotareImageClockwise_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCW.
        /// </summary>
        internal static string EditPhoto_Designer_btnRotareImageCounterclockwise_Text {
            get {
                return ResourceManager.GetString("EditPhoto_Designer_btnRotareImageCounterclockwise_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string EditPhoto_Designer_menuItemCancel_Text {
            get {
                return ResourceManager.GetString("EditPhoto_Designer_menuItemCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string EditPhoto_Designer_menuItemSave_Text {
            get {
                return ResourceManager.GetString("EditPhoto_Designer_menuItemSave_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать фото.
        /// </summary>
        internal static string EditPhotoView_Text {
            get {
                return ResourceManager.GetString("EditPhotoView_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Статус не установлен&gt;.
        /// </summary>
        internal static string Empty_Status {
            get {
                return ResourceManager.GetString("Empty_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция выполнена с ошибкой!.
        /// </summary>
        internal static string ErrorMessages_OperationIsDoneUnsuccsessfully {
            get {
                return ResourceManager.GetString("ErrorMessages_OperationIsDoneUnsuccsessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программе.
        /// </summary>
        internal static string ExtraView_AboutButtonTitle {
            get {
                return ResourceManager.GetString("ExtraView_AboutButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти из приложения.
        /// </summary>
        internal static string ExtraView_ExitButtonTitle {
            get {
                return ResourceManager.GetString("ExtraView_ExitButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справка.
        /// </summary>
        internal static string ExtraView_HelpButtonTitle {
            get {
                return ResourceManager.GetString("ExtraView_HelpButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string ExtraView_SettingsButtonTitle {
            get {
                return ResourceManager.GetString("ExtraView_SettingsButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опции.
        /// </summary>
        internal static string ExtraView_Text {
            get {
                return ResourceManager.GetString("ExtraView_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные пользователя.
        /// </summary>
        internal static string ExtraView_UserDataButtonTitle {
            get {
                return ResourceManager.GetString("ExtraView_UserDataButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error!.
        /// </summary>
        internal static string FatalError {
            get {
                return ResourceManager.GetString("FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VKontakte Windows Mobile encountered an error and needs to close!
        ///Error: {0}
        ///
        ///Additional information is available in ApplicationLog.txt file..
        /// </summary>
        internal static string FatalErrorInfo {
            get {
                return ResourceManager.GetString("FatalErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр.
        /// </summary>
        internal static string FilterText {
            get {
                return ResourceManager.GetString("FilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Первичная загрузка данных.
        /// </summary>
        internal static string FirstDataLoading {
            get {
                return ResourceManager.GetString("FirstDataLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Название не определено).
        /// </summary>
        internal static string FriendList_Noname {
            get {
                return ResourceManager.GetString("FriendList_Noname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо выбрать друга из списка.
        /// </summary>
        internal static string FriendSearchView_DontChoice {
            get {
                return ResourceManager.GetString("FriendSearchView_DontChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        internal static string FriendsList_Designer_btnFriendsAll_Text {
            get {
                return ResourceManager.GetString("FriendsList_Designer_btnFriendsAll_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новые.
        /// </summary>
        internal static string FriendsList_Designer_btnFriendsNew_Text {
            get {
                return ResourceManager.GetString("FriendsList_Designer_btnFriendsNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Онлайн.
        /// </summary>
        internal static string FriendsList_Designer_btnFriendsOnline_Text {
            get {
                return ResourceManager.GetString("FriendsList_Designer_btnFriendsOnline_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        internal static string FriendsList_Designer_btnRefresh_Text {
            get {
                return ResourceManager.GetString("FriendsList_Designer_btnRefresh_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция выполнена с ошибкой..
        /// </summary>
        internal static string FriendsList_Messages_OperationDoneUnsuccsessfully {
            get {
                return ResourceManager.GetString("FriendsList_Messages_OperationDoneUnsuccsessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск друзей.
        /// </summary>
        internal static string FriendsList_View_FilterTitle {
            get {
                return ResourceManager.GetString("FriendsList_View_FilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друзья.
        /// </summary>
        internal static string FriendsList_View_Title {
            get {
                return ResourceManager.GetString("FriendsList_View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попробуйте обновить вручную.
        /// </summary>
        internal static string FriendsListKineticListView_IfEmptyText {
            get {
                return ResourceManager.GetString("FriendsListKineticListView_IfEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        internal static string FriendsSearchListViewMenuItemBack {
            get {
                return ResourceManager.GetString("FriendsSearchListViewMenuItemBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        internal static string FriendsSearchListViewMenuItemSelect {
            get {
                return ResourceManager.GetString("FriendsSearchListViewMenuItemSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр друзей.
        /// </summary>
        internal static string FriendsSearchListViewTitle {
            get {
                return ResourceManager.GetString("FriendsSearchListViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оповещения.
        /// </summary>
        internal static string GroupNotifications {
            get {
                return ResourceManager.GetString("GroupNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление фото в альбом.
        /// </summary>
        internal static string GroupPhotos {
            get {
                return ResourceManager.GetString("GroupPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновления.
        /// </summary>
        internal static string GroupUpdate {
            get {
                return ResourceManager.GetString("GroupUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        internal static string HelpBackButton_Title {
            get {
                return ResourceManager.GetString("HelpBackButton_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наверх.
        /// </summary>
        internal static string HelpIndexButton_Title {
            get {
                return ResourceManager.GetString("HelpIndexButton_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действие....
        /// </summary>
        internal static string ImageCommentView_MenuItem_Action {
            get {
                return ResourceManager.GetString("ImageCommentView_MenuItem_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        internal static string ImageCommentView_MenuItem_Back {
            get {
                return ResourceManager.GetString("ImageCommentView_MenuItem_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Положить в мой альбом.
        /// </summary>
        internal static string ImageCommentView_MenuItem_PutInAlbum {
            get {
                return ResourceManager.GetString("ImageCommentView_MenuItem_PutInAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        internal static string ImageCommentView_MenuItem_Refresh {
            get {
                return ResourceManager.GetString("ImageCommentView_MenuItem_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить на телефоне.
        /// </summary>
        internal static string ImageCommentView_MenuItem_SavePhoto {
            get {
                return ResourceManager.GetString("ImageCommentView_MenuItem_SavePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оставить комментарий.
        /// </summary>
        internal static string ImageCommentView_MenuItem_SendComment {
            get {
                return ResourceManager.GetString("ImageCommentView_MenuItem_SendComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фото.
        /// </summary>
        internal static string ImageCommentView_Title {
            get {
                return ResourceManager.GetString("ImageCommentView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попробуйте обновить вручную.
        /// </summary>
        internal static string ImageDetailedKineticListView_IfEmptyText {
            get {
                return ResourceManager.GetString("ImageDetailedKineticListView_IfEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправитель.
        /// </summary>
        internal static string ImageDetailedList_Group_Author {
            get {
                return ResourceManager.GetString("ImageDetailedList_Group_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии.
        /// </summary>
        internal static string ImageDetailedList_Group_Comments {
            get {
                return ResourceManager.GetString("ImageDetailedList_Group_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрешение изображений.
        /// </summary>
        internal static string ImageMaxSize {
            get {
                return ResourceManager.GetString("ImageMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка изображения....
        /// </summary>
        internal static string ImageUpload {
            get {
                return ResourceManager.GetString("ImageUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный логин или пароль.
        /// </summary>
        internal static string IncorrectLoginOrPassword {
            get {
                return ResourceManager.GetString("IncorrectLoginOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient memory!.
        /// </summary>
        internal static string InsufficientMemory {
            get {
                return ResourceManager.GetString("InsufficientMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        internal static string LoginView_Button_Cancel {
            get {
                return ResourceManager.GetString("LoginView_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        internal static string LoginView_Button_Login {
            get {
                return ResourceManager.GetString("LoginView_Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная почта или логин.
        /// </summary>
        internal static string LoginView_Caption_Login {
            get {
                return ResourceManager.GetString("LoginView_Caption_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string LoginView_Caption_Password {
            get {
                return ResourceManager.GetString("LoginView_Caption_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        internal static string LoginView_Exit {
            get {
                return ResourceManager.GetString("LoginView_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для входа необходимо заполнить поля логина и пароля.
        /// </summary>
        internal static string LoginView_LoginOrPassIsEmpty {
            get {
                return ResourceManager.GetString("LoginView_LoginOrPassIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to запомнить меня.
        /// </summary>
        internal static string LoginView_Remember {
            get {
                return ResourceManager.GetString("LoginView_Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        internal static string LoginView_Text {
            get {
                return ResourceManager.GetString("LoginView_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to См. аватар.
        /// </summary>
        internal static string MainView_Button_ChangeAvatar {
            get {
                return ResourceManager.GetString("MainView_Button_ChangeAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        internal static string MainView_Button_ChangeStatus {
            get {
                return ResourceManager.GetString("MainView_Button_ChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизуйтесь с галочкой &quot;запомнить&quot;, чтобы запустить нотификатор.
        /// </summary>
        internal static string MainView_Button_NotificatorCantStart {
            get {
                return ResourceManager.GetString("MainView_Button_NotificatorCantStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        internal static string MainView_Button_Refresh {
            get {
                return ResourceManager.GetString("MainView_Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментариев.
        /// </summary>
        internal static string MainView_Label_Comments {
            get {
                return ResourceManager.GetString("MainView_Label_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друзей.
        /// </summary>
        internal static string MainView_Label_Friends {
            get {
                return ResourceManager.GetString("MainView_Label_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новостей.
        /// </summary>
        internal static string MainView_Label_FriendsNews {
            get {
                return ResourceManager.GetString("MainView_Label_FriendsNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фотографий.
        /// </summary>
        internal static string MainView_Label_FriendsPhotos {
            get {
                return ResourceManager.GetString("MainView_Label_FriendsPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщений.
        /// </summary>
        internal static string MainView_Label_Messages {
            get {
                return ResourceManager.GetString("MainView_Label_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стена.
        /// </summary>
        internal static string MainView_Label_WallMessages {
            get {
                return ResourceManager.GetString("MainView_Label_WallMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        internal static string MainView_Text {
            get {
                return ResourceManager.GetString("MainView_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkinManagerDefaultLoadingException.
        /// </summary>
        internal static string MasterForm_Initialize_SkinManagerDefaultLoadingException {
            get {
                return ResourceManager.GetString("MasterForm_Initialize_SkinManagerDefaultLoadingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkinManagerLoadingException.
        /// </summary>
        internal static string MasterForm_Initialize_SkinManagerLoadingException {
            get {
                return ResourceManager.GetString("MasterForm_Initialize_SkinManagerLoadingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я.
        /// </summary>
        internal static string MessageI {
            get {
                return ResourceManager.GetString("MessageI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        internal static string MessagesChainsList_Designer_btnRefresh {
            get {
                return ResourceManager.GetString("MessagesChainsList_Designer_btnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новое сообщение.
        /// </summary>
        internal static string MessagesChainsList_Designer_btnSentMessage {
            get {
                return ResourceManager.GetString("MessagesChainsList_Designer_btnSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщения.
        /// </summary>
        internal static string MessagesChainsList_View_Title {
            get {
                return ResourceManager.GetString("MessagesChainsList_View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попробуйте обновить вручную.
        /// </summary>
        internal static string MessagesChainsListKineticListView_IfEmptyText {
            get {
                return ResourceManager.GetString("MessagesChainsListKineticListView_IfEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение.
        /// </summary>
        internal static string MessageSend_Title {
            get {
                return ResourceManager.GetString("MessageSend_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение успешно отправлено!.
        /// </summary>
        internal static string MessagesList_Controller_Messages_MessageSentSuccessfully {
            get {
                return ResourceManager.GetString("MessagesList_Controller_Messages_MessageSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция выполнена с ошибкой..
        /// </summary>
        internal static string MessagesList_Controller_Messages_MessageSentUnsuccessfully {
            get {
                return ResourceManager.GetString("MessagesList_Controller_Messages_MessageSentUnsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия....
        /// </summary>
        internal static string MessagesList_Designer_menuItemActions_Text {
            get {
                return ResourceManager.GetString("MessagesList_Designer_menuItemActions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        internal static string MessagesList_Designer_menuItemBack_Text {
            get {
                return ResourceManager.GetString("MessagesList_Designer_menuItemBack_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string MessagesList_Designer_menuItemCancel_Text {
            get {
                return ResourceManager.GetString("MessagesList_Designer_menuItemCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Написать.
        /// </summary>
        internal static string MessagesList_Designer_menuItemSent_Text {
            get {
                return ResourceManager.GetString("MessagesList_Designer_menuItemSent_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщения.
        /// </summary>
        internal static string MessagesList_Designer_Title {
            get {
                return ResourceManager.GetString("MessagesList_Designer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наберите текст сообщения.
        /// </summary>
        internal static string MessagesList_View_MessageIsEmpty {
            get {
                return ResourceManager.GetString("MessagesList_View_MessageIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нотификация.
        /// </summary>
        internal static string MultiValueView_Text {
            get {
                return ResourceManager.GetString("MultiValueView_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий загружен.
        /// </summary>
        internal static string NewCommentUploaded {
            get {
                return ResourceManager.GetString("NewCommentUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Написать сообщение.
        /// </summary>
        internal static string NewMessage {
            get {
                return ResourceManager.GetString("NewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неудалось подключится к серверу, проверьте настройки подключения.
        /// </summary>
        internal static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough program memory to run the application. Please close some of the running applications!.
        /// </summary>
        internal static string NotEnoughMemory {
            get {
                return ResourceManager.GetString("NotEnoughMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я:.
        /// </summary>
        internal static string OutboxText {
            get {
                return ResourceManager.GetString("OutboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для выполнения операции недостаточно памяти!.
        /// </summary>
        internal static string OutOfMemory {
            get {
                return ResourceManager.GetString("OutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить.
        /// </summary>
        internal static string PasteFromClipboard {
            get {
                return ResourceManager.GetString("PasteFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сегодня.
        /// </summary>
        internal static string PhotoCommentsUpdatesList_Controller_Group_Today {
            get {
                return ResourceManager.GetString("PhotoCommentsUpdatesList_Controller_Group_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вчера.
        /// </summary>
        internal static string PhotoCommentsUpdatesList_Controller_Group_Yesterday {
            get {
                return ResourceManager.GetString("PhotoCommentsUpdatesList_Controller_Group_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция выполнена с ошибкой..
        /// </summary>
        internal static string PhotoCommentsUpdatesList_Messages_OperationDoneUnsuccsessfully {
            get {
                return ResourceManager.GetString("PhotoCommentsUpdatesList_Messages_OperationDoneUnsuccsessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новости.
        /// </summary>
        internal static string PhotoCommentsUpdatesList_View_Title {
            get {
                return ResourceManager.GetString("PhotoCommentsUpdatesList_View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет комментариев..
        /// </summary>
        internal static string PhotoCommentsUpdatesListKineticListView_IfEmptyText {
            get {
                return ResourceManager.GetString("PhotoCommentsUpdatesListKineticListView_IfEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для запуска приложения необходима Windows Mobile 5.0 и выше с тачскрином.
        /// </summary>
        internal static string PlatformSupport {
            get {
                return ResourceManager.GetString("PlatformSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновлять в роуминге.
        /// </summary>
        internal static string RenewInRoam {
            get {
                return ResourceManager.GetString("RenewInRoam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация добавлена в телефонную книжку.
        /// </summary>
        internal static string SaveNumberResponseMessage_Succsess {
            get {
                return ResourceManager.GetString("SaveNumberResponseMessage_Succsess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция выполнена с ошибкой.
        /// </summary>
        internal static string SaveNumberResponseMessage_Unsuccess {
            get {
                return ResourceManager.GetString("SaveNumberResponseMessage_Unsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно отправить пустой комментарий.
        /// </summary>
        internal static string SendComment_DontEmpty {
            get {
                return ResourceManager.GetString("SendComment_DontEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить.
        /// </summary>
        internal static string SendCommentSend {
            get {
                return ResourceManager.GetString("SendCommentSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправка комментария.
        /// </summary>
        internal static string SendCommentTitle {
            get {
                return ResourceManager.GetString("SendCommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка отправки сообщения.
        /// </summary>
        internal static string SendMessageError {
            get {
                return ResourceManager.GetString("SendMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я.
        /// </summary>
        internal static string SetGroupEndChar {
            get {
                return ResourceManager.GetString("SetGroupEndChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to А.
        /// </summary>
        internal static string SetGroupStartChar {
            get {
                return ResourceManager.GetString("SetGroupStartChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии.
        /// </summary>
        internal static string Settings_Comments {
            get {
                return ResourceManager.GetString("Settings_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не изменять.
        /// </summary>
        internal static string Settings_DoNotChange {
            get {
                return ResourceManager.GetString("Settings_DoNotChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новые друзья.
        /// </summary>
        internal static string Settings_Friends {
            get {
                return ResourceManager.GetString("Settings_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новости друзей.
        /// </summary>
        internal static string Settings_FriendsNews {
            get {
                return ResourceManager.GetString("Settings_FriendsNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фото друзей.
        /// </summary>
        internal static string Settings_FriendsPhotos {
            get {
                return ResourceManager.GetString("Settings_FriendsPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Раз в 10 минут.
        /// </summary>
        internal static string Settings_In10Min {
            get {
                return ResourceManager.GetString("Settings_In10Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Раз в 5 минут.
        /// </summary>
        internal static string Settings_In5Min {
            get {
                return ResourceManager.GetString("Settings_In5Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Раз в час.
        /// </summary>
        internal static string Settings_InHour {
            get {
                return ResourceManager.GetString("Settings_InHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщения.
        /// </summary>
        internal static string Settings_Messages {
            get {
                return ResourceManager.GetString("Settings_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выключено.
        /// </summary>
        internal static string Settings_Off {
            get {
                return ResourceManager.GetString("Settings_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 640x480.
        /// </summary>
        internal static string Settings_Res640X480 {
            get {
                return ResourceManager.GetString("Settings_Res640X480", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string Settings_View_Back {
            get {
                return ResourceManager.GetString("Settings_View_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово.
        /// </summary>
        internal static string Settings_View_Save {
            get {
                return ResourceManager.GetString("Settings_View_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщения стены.
        /// </summary>
        internal static string Settings_WallMessages {
            get {
                return ResourceManager.GetString("Settings_WallMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        internal static string SettingsView_Button_Exit {
            get {
                return ResourceManager.GetString("SettingsView_Button_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фоновая проверка событий.
        /// </summary>
        internal static string SettingsView_Group_BackGroundEventsCheck {
            get {
                return ResourceManager.GetString("SettingsView_Group_BackGroundEventsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка данных.
        /// </summary>
        internal static string SettingsView_GroupHeader {
            get {
                return ResourceManager.GetString("SettingsView_GroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомления.
        /// </summary>
        internal static string SettingsView_GroupHeader_Notifications {
            get {
                return ResourceManager.GetString("SettingsView_GroupHeader_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправка фотографий.
        /// </summary>
        internal static string SettingsView_GroupHeader_Photos {
            get {
                return ResourceManager.GetString("SettingsView_GroupHeader_Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string SettingsView_menuItemBack_Text {
            get {
                return ResourceManager.GetString("SettingsView_menuItemBack_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово.
        /// </summary>
        internal static string SettingsView_menuItemSave_Text {
            get {
                return ResourceManager.GetString("SettingsView_menuItemSave_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только через Wi-Fi.
        /// </summary>
        internal static string SettingsView_OnlyWiFi {
            get {
                return ResourceManager.GetString("SettingsView_OnlyWiFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нотификация.
        /// </summary>
        internal static string SettingsView_Renew {
            get {
                return ResourceManager.GetString("SettingsView_Renew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключить в роуминге.
        /// </summary>
        internal static string SettingsView_RenewInRoam {
            get {
                return ResourceManager.GetString("SettingsView_RenewInRoam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отображение.
        /// </summary>
        internal static string SettingsView_Representation {
            get {
                return ResourceManager.GetString("SettingsView_Representation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывать аватары.
        /// </summary>
        internal static string SettingsView_ShowAvatars {
            get {
                return ResourceManager.GetString("SettingsView_ShowAvatars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка приложения.
        /// </summary>
        internal static string SettingsView_Text {
            get {
                return ResourceManager.GetString("SettingsView_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновлять.
        /// </summary>
        internal static string SettingsView_Update {
            get {
                return ResourceManager.GetString("SettingsView_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При старте.
        /// </summary>
        internal static string SettingsView_WhileStatrted {
            get {
                return ResourceManager.GetString("SettingsView_WhileStatrted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действие....
        /// </summary>
        internal static string SharePhotoView_MenuItem_Action {
            get {
                return ResourceManager.GetString("SharePhotoView_MenuItem_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string SharePhotoView_MenuItem_Cancel {
            get {
                return ResourceManager.GetString("SharePhotoView_MenuItem_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По часовой стрелке.
        /// </summary>
        internal static string SharePhotoView_MenuItem_RC {
            get {
                return ResourceManager.GetString("SharePhotoView_MenuItem_RC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Против часовой стрелки.
        /// </summary>
        internal static string SharePhotoView_MenuItem_RCC {
            get {
                return ResourceManager.GetString("SharePhotoView_MenuItem_RCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить в альбом.
        /// </summary>
        internal static string SharePhotoView_MenuItem_Send {
            get {
                return ResourceManager.GetString("SharePhotoView_MenuItem_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть файл изображения.
        /// </summary>
        internal static string ShareView_Button_Open {
            get {
                return ResourceManager.GetString("ShareView_Button_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сделать снимок.
        /// </summary>
        internal static string ShareView_Button_Photo {
            get {
                return ResourceManager.GetString("ShareView_Button_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сменить статус.
        /// </summary>
        internal static string ShareView_Button_Write {
            get {
                return ResourceManager.GetString("ShareView_Button_Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус и фото.
        /// </summary>
        internal static string ShareView_Header {
            get {
                return ResourceManager.GetString("ShareView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поделиться.
        /// </summary>
        internal static string ShareView_Title {
            get {
                return ResourceManager.GetString("ShareView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запустить оповещение.
        /// </summary>
        internal static string StartNotification {
            get {
                return ResourceManager.GetString("StartNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О чём Вы думаете?.
        /// </summary>
        internal static string StatusControl_TextSubstitute {
            get {
                return ResourceManager.GetString("StatusControl_TextSubstitute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сегодня.
        /// </summary>
        internal static string StatusUpdatesList_Controller_Group_Today {
            get {
                return ResourceManager.GetString("StatusUpdatesList_Controller_Group_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вчера.
        /// </summary>
        internal static string StatusUpdatesList_Controller_Group_Yesterday {
            get {
                return ResourceManager.GetString("StatusUpdatesList_Controller_Group_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии.
        /// </summary>
        internal static string StatusUpdatesList_Designer_btnPhotoCommentsUpdates_Text {
            get {
                return ResourceManager.GetString("StatusUpdatesList_Designer_btnPhotoCommentsUpdates_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        internal static string StatusUpdatesList_Designer_btnRefresh_Text {
            get {
                return ResourceManager.GetString("StatusUpdatesList_Designer_btnRefresh_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друзья.
        /// </summary>
        internal static string StatusUpdatesList_Designer_btnStatusUpdates_Text {
            get {
                return ResourceManager.GetString("StatusUpdatesList_Designer_btnStatusUpdates_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция выполнена с ошибкой..
        /// </summary>
        internal static string StatusUpdatesList_Messages_OperationDoneUnsuccsessfully {
            get {
                return ResourceManager.GetString("StatusUpdatesList_Messages_OperationDoneUnsuccsessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новости.
        /// </summary>
        internal static string StatusUpdatesList_View_Title {
            get {
                return ResourceManager.GetString("StatusUpdatesList_View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попробуйте обновить вручную.
        /// </summary>
        internal static string StatusUpdatesListKineticListView_IfEmptyText {
            get {
                return ResourceManager.GetString("StatusUpdatesListKineticListView_IfEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остановить оповещение.
        /// </summary>
        internal static string StopNotification {
            get {
                return ResourceManager.GetString("StopNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сегодня.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Еще.
        /// </summary>
        internal static string toolBar_Extras {
            get {
                return ResourceManager.GetString("toolBar_Extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друзья.
        /// </summary>
        internal static string toolBar_Friends {
            get {
                return ResourceManager.GetString("toolBar_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Беседы.
        /// </summary>
        internal static string toolBar_Messages {
            get {
                return ResourceManager.GetString("toolBar_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новости.
        /// </summary>
        internal static string toolBar_News {
            get {
                return ResourceManager.GetString("toolBar_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поделиться.
        /// </summary>
        internal static string toolBar_Photos {
            get {
                return ResourceManager.GetString("toolBar_Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всегда.
        /// </summary>
        internal static string UpdateAlways {
            get {
                return ResourceManager.GetString("UpdateAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закачивать статусы друзей.
        /// </summary>
        internal static string UpdateFriendsStatus {
            get {
                return ResourceManager.GetString("UpdateFriendsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступна версия для скачивания.
        /// </summary>
        internal static string UpdateInfo_Message_VersionAvaliable {
            get {
                return ResourceManager.GetString("UpdateInfo_Message_VersionAvaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позже.
        /// </summary>
        internal static string UpdateInfoDialogControl_Buttons_Cancel {
            get {
                return ResourceManager.GetString("UpdateInfoDialogControl_Buttons_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        internal static string UpdateInfoDialogControl_Buttons_Exit {
            get {
                return ResourceManager.GetString("UpdateInfoDialogControl_Buttons_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игнорировать.
        /// </summary>
        internal static string UpdateInfoDialogControl_Buttons_Skip {
            get {
                return ResourceManager.GetString("UpdateInfoDialogControl_Buttons_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        internal static string UpdateInfoDialogControl_Buttons_Update {
            get {
                return ResourceManager.GetString("UpdateInfoDialogControl_Buttons_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение не выбрано!.
        /// </summary>
        internal static string UploadPhoto_Controller_ModifyPhotoResponseMessage {
            get {
                return ResourceManager.GetString("UploadPhoto_Controller_ModifyPhotoResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображения JPG|*.jpg|Изображения BMP|*.bmp|Изображения GIF|*.gif|Изображения PNG|*.png|Все файлы (*.*)|*.*.
        /// </summary>
        internal static string UploadPhoto_Controller_newOpenFileDialog_Filter {
            get {
                return ResourceManager.GetString("UploadPhoto_Controller_newOpenFileDialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл не существует!.
        /// </summary>
        internal static string UploadPhoto_Controller_ResponseMessage_FileDoesNotExist {
            get {
                return ResourceManager.GetString("UploadPhoto_Controller_ResponseMessage_FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка преобразования файла!.
        /// </summary>
        internal static string UploadPhoto_Controller_ResponseMessage_ImageConvertingError {
            get {
                return ResourceManager.GetString("UploadPhoto_Controller_ResponseMessage_ImageConvertingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение отправлено в альбом.
        /// </summary>
        internal static string UploadPhoto_Controller_ResponseMessage_ImageSuccessfullyDownloaded {
            get {
                return ResourceManager.GetString("UploadPhoto_Controller_ResponseMessage_ImageSuccessfullyDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение не загружено.
        /// </summary>
        internal static string UploadPhoto_Controller_UploadPhotoResponseMessage_ImageIsNotDownloaded {
            get {
                return ResourceManager.GetString("UploadPhoto_Controller_UploadPhotoResponseMessage_ImageIsNotDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение не выбрано.
        /// </summary>
        internal static string UploadPhoto_Controller_UploadPhotoResponseMessage_ImageIsNotPicked {
            get {
                return ResourceManager.GetString("UploadPhoto_Controller_UploadPhotoResponseMessage_ImageIsNotPicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С диска.
        /// </summary>
        internal static string UploadPhoto_Designer_btnLoadPhotoFromDisk_Text {
            get {
                return ResourceManager.GetString("UploadPhoto_Designer_btnLoadPhotoFromDisk_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        internal static string UploadPhoto_Designer_btnModifyPhoto_Text {
            get {
                return ResourceManager.GetString("UploadPhoto_Designer_btnModifyPhoto_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С камеры.
        /// </summary>
        internal static string UploadPhoto_Designer_btnSnapPhotoWithinCamera_Text {
            get {
                return ResourceManager.GetString("UploadPhoto_Designer_btnSnapPhotoWithinCamera_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        internal static string UploadPhoto_Designer_menuItemBack_Text {
            get {
                return ResourceManager.GetString("UploadPhoto_Designer_menuItemBack_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить.
        /// </summary>
        internal static string UploadPhoto_Designer_menuItemUpload_Text {
            get {
                return ResourceManager.GetString("UploadPhoto_Designer_menuItemUpload_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В альбом.
        /// </summary>
        internal static string UploadPhoto_Designer_rbMobileAlbum_Text {
            get {
                return ResourceManager.GetString("UploadPhoto_Designer_rbMobileAlbum_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На аватар.
        /// </summary>
        internal static string UploadPhoto_Designer_rbPrivateAlbum_Text {
            get {
                return ResourceManager.GetString("UploadPhoto_Designer_rbPrivateAlbum_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фото.
        /// </summary>
        internal static string UploadPhoto_View_Title {
            get {
                return ResourceManager.GetString("UploadPhoto_View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фото.
        /// </summary>
        internal static string UploadPhotoView_Header {
            get {
                return ResourceManager.GetString("UploadPhotoView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбери картинку&lt;br&gt;или&lt;br&gt;сделай снимок.
        /// </summary>
        internal static string UploadPhotoView_VoidPhotoLabel {
            get {
                return ResourceManager.GetString("UploadPhotoView_VoidPhotoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы действительно хотите очистить локальный кэш?.
        /// </summary>
        internal static string UserData_ClearCache {
            get {
                return ResourceManager.GetString("UserData_ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы действительно хотите стереть пароль?.
        /// </summary>
        internal static string UserData_ClearPass {
            get {
                return ResourceManager.GetString("UserData_ClearPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить кэш.
        /// </summary>
        internal static string UserDataView_Button_ClearCache {
            get {
                return ResourceManager.GetString("UserDataView_Button_ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сменить пользователя.
        /// </summary>
        internal static string UserDataView_Button_ClearPass {
            get {
                return ResourceManager.GetString("UserDataView_Button_ClearPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные пользователя.
        /// </summary>
        internal static string UserDataView_Text {
            get {
                return ResourceManager.GetString("UserDataView_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш аккаунт временно заблокирован, попробуйте позже..
        /// </summary>
        internal static string VK_ERRORS_AccountBloked {
            get {
                return ResourceManager.GetString("VK_ERRORS_AccountBloked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сессия истекла.
        /// </summary>
        internal static string VK_ERRORS_ExpireSession {
            get {
                return ResourceManager.GetString("VK_ERRORS_ExpireSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Флуд-контроль.
        /// </summary>
        internal static string VK_ERRORS_FloodControl {
            get {
                return ResourceManager.GetString("VK_ERRORS_FloodControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный логин или пароль.
        /// </summary>
        internal static string VK_ERRORS_IncorrectLoginOrPassword {
            get {
                return ResourceManager.GetString("VK_ERRORS_IncorrectLoginOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удается произвести подключение к Интернет. Проверьте настройки подключения.
        /// </summary>
        internal static string VK_ERRORS_NoConnection {
            get {
                return ResourceManager.GetString("VK_ERRORS_NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка! Невозможно получить данные Вашего профиля.
        ///Если Вы недавно создавали аккаунт, то для доступа к сервису Вам необходимо выполнить привязку к мобильному телефону на сайте vkontakte.ru..
        /// </summary>
        internal static string VK_ERRORS_NoLinkedApplication {
            get {
                return ResourceManager.GetString("VK_ERRORS_NoLinkedApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нестандартная ошибка на сервере, повторите операцию.
        /// </summary>
        internal static string VK_ERRORS_NonstandardServerError {
            get {
                return ResourceManager.GetString("VK_ERRORS_NonstandardServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не сохранен токен авторизации.
        /// </summary>
        internal static string VK_ERRORS_NoSavedToken {
            get {
                return ResourceManager.GetString("VK_ERRORS_NoSavedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция запрещена настройками приватности.
        /// </summary>
        internal static string VK_ERRORS_OperationIsProhibitedByPrivacy {
            get {
                return ResourceManager.GetString("VK_ERRORS_OperationIsProhibitedByPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервер недоступен.
        /// </summary>
        internal static string VK_ERRORS_ServerUnavalible {
            get {
                return ResourceManager.GetString("VK_ERRORS_ServerUnavalible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка запуска сервиса.
        /// </summary>
        internal static string VK_ERRORS_ServiceStartError {
            get {
                return ResourceManager.GetString("VK_ERRORS_ServiceStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестная ошибка.
        /// </summary>
        internal static string VK_ERRORS_UnknownError {
            get {
                return ResourceManager.GetString("VK_ERRORS_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция завершена неуспешно. Попробуйте еще раз.
        /// </summary>
        internal static string VK_ERRORS_UnsuccessfullOperation {
            get {
                return ResourceManager.GetString("VK_ERRORS_UnsuccessfullOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стена.
        /// </summary>
        internal static string WallPostList_View_Title {
            get {
                return ResourceManager.GetString("WallPostList_View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стена пуста..
        /// </summary>
        internal static string WallPostListKineticListView_IfEmptyText {
            get {
                return ResourceManager.GetString("WallPostListKineticListView_IfEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть ссылку во внешнем браузере?.
        /// </summary>
        internal static string WebBrowser_dialog_Text {
            get {
                return ResourceManager.GetString("WebBrowser_dialog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        internal static string WebBrowser_menuItemBack_Text {
            get {
                return ResourceManager.GetString("WebBrowser_menuItemBack_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        internal static string WebBrowser_menuItemToApp_Text {
            get {
                return ResourceManager.GetString("WebBrowser_menuItemToApp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фото.
        /// </summary>
        internal static string WebBrowser_View_Album_Title {
            get {
                return ResourceManager.GetString("WebBrowser_View_Album_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль друга.
        /// </summary>
        internal static string WebBrowser_View_FriendProfile_Title {
            get {
                return ResourceManager.GetString("WebBrowser_View_FriendProfile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справка.
        /// </summary>
        internal static string WebBrowser_View_Help_Title {
            get {
                return ResourceManager.GetString("WebBrowser_View_Help_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправка подарка.
        /// </summary>
        internal static string WebBrowser_View_SendGift_Title {
            get {
                return ResourceManager.GetString("WebBrowser_View_SendGift_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно перейти по сылке.
        /// </summary>
        internal static string WebBrowser_View_UriError {
            get {
                return ResourceManager.GetString("WebBrowser_View_UriError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        internal static string WebBrowser_View_UserProfile_Title {
            get {
                return ResourceManager.GetString("WebBrowser_View_UserProfile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправка сообщения.
        /// </summary>
        internal static string WebBrowser_View_WriteMessage_Title {
            get {
                return ResourceManager.GetString("WebBrowser_View_WriteMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вчера.
        /// </summary>
        internal static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
